### ISSUE TITLE
As imagens estão quebrando quando faço download na minha máquina

### ISSUE THREAD

**Issue by alicepaixao** [stelleal/Projeto-01-Dungeon-Guides#1]
<img width="1783" alt="Captura de Tela 2021-11-27 às 09 11 52" src="https://user-images.githubusercontent.com/30302741/143680811-d9992e5c-ebe5-4611-a225-ac80f279d40b.png">

Para funcionar fiz o seguinte ajuste
Antes <img src="/Imagens/Logo.png"
Depois <img src="Imagens/Logo.png"
Retirei a barra para todas imagens

**Comment by stelleal** [comment]
Obrigado por informar.
Pelo visto não estava dando erro para mim pois estava usando o Live Server para acompanhar o site.
Mudei os links com ./ e as imagens com ../
Creio que assim corrigirá os erros.
